name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual runs
  push:
    branches: [ "main" ]

jobs:
  generate:
    runs-on: ubuntu-latest  # This is fine - runs on GitHub's servers
    permissions:
      contents: write  # Required to push the SVG

    steps:
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-dark
            dist/snake.svg?palette=github-light

      - name: Commit and Push
        uses: actions-js/push@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          directory: dist